server:
  port: 8763
spring:
  application:
    name: admin-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bosen-once/test.git config-git/
          search-paths: repo
          default-label: main
