server:
  port: 9999
spring:
  application:
    name: test-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
management:
  security:
    enabled: false
foo: this is test params foo1
